# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["svn.io"]
description = "Ask the universe."
language = "javascript"
manifest_version = 2
name = "Ask the universe."
service_id = "ltUTz8OJe4NVSKkoy1gNE2"

[scripts]
  build = "npm run build"

[local_server]
  [local_server.backends]
    [local_server.backends.vercel]
      url = "https://api.svn.sh"
      override_host = "api.svn.sh"
